Repository JanSeemann92/Geosoftware1-2021-Final, pull requests merged in 2021-09, with the labels that each got.

#2 ability to add and show geometries on map
  frontend/public/index.html
  frontend/src/Providers.js
  frontend/src/map/Map.js
  frontend/src/map/MapContext.js
  frontend/src/map/index.js
  frontend/src/map/map.css
  frontend/src/sight/SightForm.js
  frontend/src/sight/SightList.js
  frontend/src/tour/TourList.js
Labels: enhancement

#4 add detail view sights and enhancements
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/TruncateText.js
  frontend/src/component/index.js
  frontend/src/map/components/SightPopup.js
  frontend/src/sight/SightForm.js
  frontend/src/sight/SightList.js
  frontend/src/sight/component/SightTile.js
  frontend/src/sight/component/index.js
  frontend/src/tour/TourDetails.js
  frontend/src/tour/TourForm.js
  frontend/src/tour/TourList.js
  frontend/src/tour/routes.js
Labels: enhancement

#5 add busradar and weather
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/api-busradar.js
  backend/src/api-open-weather.js
  backend/src/server.js
  frontend/src/Providers.js
  frontend/src/app/About.js
  frontend/src/app/App.js
  frontend/src/app/AppBar.js
  frontend/src/app/AppContext.js
  frontend/src/app/CreateResource.js
  frontend/src/app/index.js
  frontend/src/common/api.js
  frontend/src/map/MapContext.js
  frontend/src/map/components/SightPopup.js
  frontend/src/map/hooks/useSightsOnMap.js
  frontend/src/sight/SightDetails.js
  frontend/src/sight/SightForm.js
  frontend/src/sight/SightList.js
  frontend/src/sight/component/SightTile.js
  frontend/src/sight/routes.js
  frontend/src/tour/TourDetails.js
  frontend/src/tour/TourForm.js
  frontend/src/tour/TourList.js
Labels: bug, enhancement

#9 update readme and publish containers
  README.md
  docker-compose.yaml
Labels: documentation

#10 add api doc
  backend/README.md
  backend/src/server.js
  frontend/README.md
Labels: documentation

#11 fix minor things
  frontend/src/app/App.js
  frontend/src/app/CreateResource.js
Labels: bug
